/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AppNavbar: typeof import('./src/components/AppNavbar.vue')['default']
    BaseInput: typeof import('./src/components/BaseInput.vue')['default']
    BaseTextarea: typeof import('./src/components/BaseTextarea.vue')['default']
    BaseUpload: typeof import('./src/components/BaseUpload.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
